# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true	# https://help.github.com/articles/removing-relative-permalinks

# Setup
title:               Galaxy's World
tagline:             '银河雪尘'
description:         'My Blog with <a href="http://jekyllrb.com" target="_blank">Jekyll</a>. Written by <a href="https://twitter.com/galaxy001" target="_blank">@galaxy001</a>.'
url:                 https://galaxysd.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yuuki Galaxy
  url:               https://twitter.com/galaxy001
  email:             galaxy001(at)gmail.com

# Custom vars
version:             1.0.0

# https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll
## Changeable
kramdown:
  input: GFM
  hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate

## Constant
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false

# Doc
# https://github.com/blog/2100-github-pages-jekyll-3
markdown: kramdown

# added by Galaxy
exclude: ["README.md", "Rakefile"]
permalink: /:categories/:year:month:day/:title
timezone: Asia/Hong_Kong
